//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiLast.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStaff
    {
        public int id { get; set; }
        public string shortAddress { get; set; }
        public string numberPhone { get; set; }
        public string emailAddres { get; set; }
        public byte[] imageLink { get; set; }
    }
}
